### ISSUE TITLE
Probably worth mentioning the performance issues

### ISSUE THREAD

**Issue by quinnj** [cjprybol/uCSV.jl#1]
While a few of the API improvements of this package are notable, it makes me uncomfortable that this got registered. Most cases of delimited file parsing are performance-sensitive, which is why any new library in any language pretty much always comes w/ benchmarks. While the idea of "relying on Base functions" might seem simple, the implementation here is going to be a drastic problem for users who need performance. I think it'd be prudent to put a big disclaimer that for performance, users should be directed to CSV.jl/TextParse.jl.

For me personally, I'm disappointed that it was felt necessary to create yet another parsing package. The julia community has typically been excellent at collaboration and I've personally tried to be as approachable and open to collaboration as possible with CSV.jl. More than happy to help people understand the internals and how to go about making changes. Part of the complexity of these packages is precisely because performance is so critical.

**Comment by cjprybol** [comment]
Hey Jacob, Thanks for the feedback! I'm sorry it makes you uncomfortable that this got registered. I wish you had said so sooner, either after the [Discourse post](https://discourse.julialang.org/t/ann-ucsv-jl/6162) or during the 24-hour comment window while the PR was open in METADATA. This package is very much an experimental prototype of what I would like CSV.jl to offer as a user-facing API, and I would have been happy to leave it unregistered if anyone had opened up a discussion to work out a path towards that goal. No one said anything, and I presume many new users (the target audience I think would benefit most from this package and provide the most feedback) would shy away from using an unregistered package, so I registered it in hope that I would get feedback from others. Of course, if you didn't check your email over the weekend to get any of those notifications then I can indeed imagine that the package registration came as a suprise, but I tried to make the announcement open to all and invited feedback on the announcement post, so I'm not sure what else I could have done to make the release less uncomfortable for you.

[Benchmarks are openly viewable in the documentation](https://cjprybol.github.io/uCSV.jl/latest/man/benchmarks.html), along with a disclaimer at the top to clarify that the benchmarks aren't necessarily the best reflection of how performant CSV.jl and TextParse.jl can be. Given that neither CSV.jl or TextParse.jl have posted benchmarks (that I'm aware of) in their READMEs or documentation, that seems like a moot point. This package is also faster on the smaller datasets than CSV.jl, not slower, and I disagree that the implementation here is going to be a drastic problem for users who need performance. Sure, if someone needs to create a data processing pipeline that meets a clients strict requirements for speed and memory usage, this implementation may not be the right tool for them. But in my view, it's easier to prototype out a full API and improve performance under the hood of a stable platform (even if it takes a while) than it is to try and expand and refactor the API of a package that has already locked itself into an optimization approach based on the existing API. I started working on adding these features to CSV.jl way back when I responded to [this issue](https://github.com/JuliaData/CSV.jl/issues/86#issuecomment-320856377). It took me about a month before I threw in the towel on refactoring CSV because I found the implementation too complex. It took me ~2 weeks to get this package from nothing to an API that offers more and is better documented than both CSV.jl and TextParse. Yes, I could have asked you and/or Shashi for help to expand the capabilities of those packages, but you're both very busy developers working on many things around the Julia community. I know your time is valuable and I didn't expect you'd have enough of it laying around to get me as up-to-speed as I needed to be to get the vision I had in my head turned into reality in either of those packages in a reasonable amount of time. One last comment on performance, I consider performance very secondary to correctness and usability. This package (to the best of my knowledge) parses datasets more accurately, and fails in far more informative ways than either of the current offerings. I would much rather wait 2-10x longer for my naive, based-on-base, implementation here to know that it will either 1) give me the correct output, or 2) tell me how to get the correct ouptut on the next parsing attempt. I can wait 10 minutes for a multi-Gb file to parse, but I cannot afford to lose 1/2 a day or more debugging an opaque error message when I'm up against a deadline.

Please don't interpret the release of this package as a personal knock against you or the laudible work that you've done in CSV.jl. I 100% agree that you and the Julia community in general create a very open, approachable, and friendly environment for collaboration. I wouldn't be working with Julia if that weren't the case. I love working on and helping to develop Julia, and hope that I can continue to do so in a way that is constructive, and not at all destructive, for the community. In this particular case, I hope you can view it for what it actually is: A necessary concession that I had to make in order to continue using Julia for my research and making progress towards my PhD. As you might imagine, convincing an academic advisor in the life sciences that spending significant amounts of time developing a pre-1.0 language while existing options (R and Python) are perfectly suitable for what I need to do on a day to day basis is a hard sell. I needed a wrench that worked when I needed it so I could continue to make progress on my computational work and spend more time focusing on the cell work I do in the wet lab. I was unsatisfied with the existing wrenches, so I built a new one. It wouldn't bother me a bit if it wasn't used by a single other person.

**Comment by quinnj** [comment]
I just think it's ultimately the users that lose out the most in this situation; now they have (at least) _3_ different delimited file parser packages to have to consider (not including the implementation in Base!) when they need to read a delimited file in their workflow. I guess this is mainly inevitable as the ecosystem grows, but I would hope that we could do better than R, where you have to consider 3-5 packages for _any_ operation you want to do in the language.

The benchmark I just did locally was comparing CSV.jl vs. uCSV.jl on [this file](https://github.com/JuliaData/CSV.jl/blob/master/test/test_files/pandas_zeros.csv), where the difference was `0.1s` vs `5.0s`, which is where I was mostly worried about performance.

**Comment by cjprybol** [comment]
This criticism seems unfair. I think the users lose when we, as developers, aren't being forthcoming about the limitations in existing offerings and stifle exploring new options and ideas. You also still haven't offered to help integrate this with CSV.jl...

Also, that file is tested in the benchmarks published in the docs as 0s-1s, where this implementation beats CSV.jl when normalized to the same output. I would appreciate you sharing the code when making assertions like that.

**Comment by quinnj** [comment]
Should I be doing anything different than
```julia
julia> @time df = CSV.read("pandas_zeros.csv");
  0.101034 seconds (3.88 k allocations: 38.411 MiB, 4.91% gc time)

julia> @time df = uCSV.read("pandas_zeros.csv");
  5.053737 seconds (12.38 M allocations: 612.491 MiB, 5.10% gc time)
```
?

**Comment by cjprybol** [comment]
I would start by ensuring that you're comparing fresh sessions to fresh sessions and compiled runs against compiled runs

```julia
Cameron@MacBook-Pro-9:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1-pre.3 (2017-09-14 17:43 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 4aa661a0c1* (18 days old release-0.6)
|__/                   |  x86_64-apple-darwin16.7.0

julia> using uCSV, CSV, DataFrames
INFO: Recompiling stale cache file /Users/Cameron/.julia/lib/v0.6/uCSV.ji for module uCSV.
INFO: Recompiling stale cache file /Users/Cameron/.julia/lib/v0.6/CSV.ji for module CSV.

julia> file = joinpath(homedir(), "Downloads", "pandas_zeros.csv")
"/Users/Cameron/Downloads/pandas_zeros.csv"

julia> @time df1 = DataFrame(uCSV.read(file, header=1));
  5.360665 seconds (13.33 M allocations: 664.899 MiB, 4.65% gc time)

julia> @time df2 = CSV.read(file);
 10.688837 seconds (10.18 M allocations: 345.178 MiB, 3.28% gc time)

julia> @assert df1 == df2

julia> @time df1 = DataFrame(uCSV.read(file, header=1));
  2.457674 seconds (11.10 M allocations: 551.887 MiB, 7.28% gc time)

julia> @time df2 = CSV.read(file);
  0.170238 seconds (5.00 M allocations: 114.598 MiB, 10.57% gc time)

julia> Pkg.status()
2 required packages:
 - CSV                           0.1.5+             master
 - uCSV                          0.0.1
14 additional packages:
 - BinDeps                       0.7.0
 - CategoricalArrays             0.2.1
 - Compat                        0.32.0
 - DataFrames                    0.10.1+            master
 - DataStreams                   0.2.0
 - DataStructures                0.7.2
 - Nulls                         0.0.6
 - Reexport                      0.0.3
 - SHA                           0.5.1
 - SortingAlgorithms             0.1.1
 - SpecialFunctions              0.3.3
 - StatsBase                     0.19.0
 - URIParser                     0.2.0
 - WeakRefStrings                0.3.1
```

Please open a new issue if you have anything constructive to add
