### ISSUE TITLE
Refer users to CSV.jl

### ISSUE THREAD

**Issue by KronosTheLate** [cjprybol/uCSV.jl#19]
It seems like this project is not actively maintained, and limited in capability. Would not not be better to direct users to well-established and tested packages like CSV.jl?

**Comment by cjprybol** [comment]
> It seems like this project is not actively maintained

I still use it daily in production workflows - it hasn't needed maintenance or bug fixes because it's been incredible stable due to its simplicity

> limited in capability

users are able to provide their own parsing functions, a feature many delimited parsing tools do not provide, so I disagree on being limited in capability.

> Would not not be better to direct users to well-established and tested packages like CSV.jl?

I don't advertise it to others as being superior to CSV.jl, but this package exists because it was able to parse many formats not parseable by CSV.jl at the time of its creation. I wouldn't encourage users to choose this package over CSV.jl if CSV.jl meets their needs, but if a user finds this package because CSV.jl does not meet their needs, I wouldn't want to discourage them in the README.md from even trying it.

This package in fact has superior code coverage and testing quality to CSV.jl, based on the published tests in the repositories

https://app.codecov.io/gh/JuliaData/CSV.jl
https://coveralls.io/github/cjprybol/uCSV.jl?branch=master

**Comment by KronosTheLate** [comment]
That is a much better answer than I anticipated, thanks! I just though that this was another one of the CSV packages that were created once upon a time, and solved some usecase then, but have since been surpassed by CSV.jl in terms of capabilites. It seems like this is an active project, that things it can bring something to the table. Good to see ^_^

Two further questions:
1) Would you be interested in making what is possible in this package, possible in CSV.jl? It seems like the best way to provide the functionality to users, as this is a smaller and harder to discover package.
2) I am trying to put together a page for comparing alternatives for working with CSV files and other delimited files, as part of [juliapackagecomparisons](https://juliapackagecomparisons.github.io/). Would you be interested in fleshing out the pros and cons of your package on that page? An entry for this package should be visible in [this subsection](https://juliapackagecomparisons.github.io/comparisons/dataio/fileio/index.html#ucsvjl) once the push I just made goes live on the main page.

**Comment by cjprybol** [comment]
> 1. Would you be interested in making what is possible in this package, possible in CSV.jl? It seems like the best way to provide the functionality to users, as this is a smaller and harder to discover package.

I like this in principle but can't volunteer to do that work at this time. If you or others would be interested in confirming that CSV.jl is capable of everything that is package is capable of, and adding any missing capability gaps, then I agree that would be helpful to users and the community.

> 2. I am trying to put together a page for comparing alternatives for working with CSV files and other delimited files, as part of [juliapackagecomparisons](https://juliapackagecomparisons.github.io/). Would you be interested in fleshing out the pros and cons of your package on that page? An entry for this package should be visible in [this subsection](https://juliapackagecomparisons.github.io/comparisons/dataio/fileio/index.html#ucsvjl) once the push I just made goes live on the main page.

This is a nice project, thanks for producing it. I don't have anything else I'd like to add.
